### ISSUE TITLE
Monitor displays incorrect frames

### ISSUE THREAD

**Issue by GDYendell** [brunoseivam/ADEiger#2]
I am finding that if I run the monitor for a while it starts skipping back frames and eventually just loops through the same 3. I have only monitored the UniqueID; I am not sure if the actual image is changing as they are difficult to distinguish with our current setup. Have you see this behaviour? Below is a camonitor output for an acquisition.

> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:40:47.728487 0  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:14.008511 1  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:14.345749 2  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:14.640621 1  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:17.336821 18  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:17.641017 1  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:18.050034 19  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:18.582853 21  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:20.042707 29  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:20.508098 30  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:20.988500 32  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:21.462700 34  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:21.940167 36  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:23.037447 42  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:23.463562 36  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:23.979779 46  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:24.700359 49  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:25.462602 53  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:25.899532 49  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:26.309442 56  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:26.787437 58  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:27.329125 60  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:27.870419 62  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:28.434574 64  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:29.690028 70  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:30.176814 72  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:31.203621 77  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:31.702919 79  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:32.181898 81  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:32.648385 79  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:34.104590 90  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:34.627100 93  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:35.117086 95  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:35.626182 97  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:37.073899 105  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:37.580719 107  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:38.336526 111  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:38.806315 107  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:39.634976 116  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:40.353763 120  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:41.191752 124  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:41.701808 126  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:42.747081 132  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:43.269356 134  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:45.225107 145  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:45.707923 147  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:46.174182 149  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:46.651029 151  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:47.015336 149  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:47.448482 151  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:48.221025 157  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:48.709950 159  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:49.206555 161  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:49.724270 163  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:50.438019 166  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:50.886493 168  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:51.913451 173  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:52.348784 175  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:52.647548 173  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:53.073070 175  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:53.530320 179  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:54.289776 182  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:54.854934 185  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:55.346149 187  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:55.818782 189  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:56.317914 191  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:56.771130 189  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:57.222268 194  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:57.694729 196  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:58.647959 201  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:59.099547 203  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:43:59.846175 206  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:00.621100 210  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:01.550759 215  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:02.092489 217  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:02.518027 219  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:02.856753 220  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:03.341005 221  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:04.067209 224  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:05.078902 230  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:05.559431 232  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:06.029514 230  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:06.344249 232  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:07.596640 241  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:07.972522 232  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:08.310166 241  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:09.121703 247  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:09.604630 249  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:09.904343 247  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:10.689911 253  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:11.058885 247  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:11.565747 253  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:12.285147 258  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:12.806876 260  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:13.331111 262  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:13.818516 264  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:14.324953 266  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:15.268954 271  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:15.714971 273  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:16.190107 275  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:16.762790 277  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:17.259111 279  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:17.756321 281  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:18.582797 285  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:19.103345 287  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:19.553229 285  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:20.086261 290  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:21.088961 295  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:21.612903 297  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:22.159389 299  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:22.619264 297  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:23.152909 303  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:23.738888 305  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:24.223593 307  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:24.680056 309  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:25.163322 307  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:25.579467 309  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:27.238548 319  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:27.980865 322  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:28.355903 319  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:28.675995 324  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:28.977614 322  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:29.280002 324  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:29.578299 325  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:30.014204 326  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:30.555020 328  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:31.029679 326  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:31.559612 331  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:32.169550 334  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:32.748529 336  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:33.281677 338  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:33.948461 341  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:34.492887 343  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:35.357189 347  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:36.256869 351  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:37.039725 354  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:37.714178 357  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:38.240318 359  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:39.381818 364  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:40.001652 366  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:40.556879 368  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:41.104824 371  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:41.937745 374  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:42.485242 376  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:42.868769 374  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:43.350529 379  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:43.935527 374  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:44.556381 382  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:45.172716 385  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:45.712470 387  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:46.145828 385  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:46.950371 392  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:47.458916 394  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:48.526761 399  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:49.279283 402  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:49.800141 404  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:50.193170 402  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:50.665921 407  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:51.171276 409  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:52.533401 415  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:53.021822 417  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:53.517894 419  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:53.992440 421  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:54.289885 422  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:54.590581 419  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:54.888781 421  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:55.185591 422  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:55.481285 419  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:55.776435 421  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:56.076193 422  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:56.373771 419  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:56.670046 421  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:56.971199 422  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:57.266710 419  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:57.566720 421  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:57.865139 422  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:58.158749 419  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:58.456417 421  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:58.753137 422  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:59.054082 419  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:59.351810 421  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:59.646869 422  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:44:59.944337 419  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:45:00.242758 421  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:45:00.542247 422  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:45:00.836984 419  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:45:01.131852 421  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:45:01.427826 422  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:45:01.726468 419  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:45:02.029741 421  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:45:02.324022 422  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:45:02.619016 419  
> BL02I-EA-EIGER-01:MON:UniqueId_RBV 2017-06-08 15:45:02.913781 421

**Comment by brunoseivam** [comment]
Hi @GDYendell ,

As I look at the code I see that actually uniqueId is not being set on `pImage`, so the numbers you see are most likely from the "recycled" NDArrays from the pool. I suspect the actual contents of the images should be correct.

I will push a fix to this issue
