### ISSUE TITLE
TriggerMode selection is incorrectly mapped to rest parameter

### ISSUE THREAD

**Issue by GDYendell** [brunoseivam/ADEiger#6]
Currently the allowed_values of trigger_mode are read in and indexed by the TriggerMode PV. However, the enums are defined in a different order, so there needs to be some logic using an explicit mapping between the two.

EPICS Record:   [ 0] Internal Series [ 1] Internal Enable [ 2] External Series [ 3] External Enable
Eiger trigger_mode: ["ints",                     "exts",                     "inte",                      "exte"]

This is assuming that neither Dectris nor AreaDetector want to re-order their values, which I expect is the case.

**Comment by brunoseivam** [comment]
Good catch! I guess I never triggered this bug because we only use the first and last modes here...

**Comment by GDYendell** [comment]
Thanks, Bruno!
